Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -55,7 +55,13 @@ jobs:
 
       - name: Run TestNG XML file
         if: inputs.testng_file != null
-        run: mvn clean test -DtestType=${{ inputs.testng_file }}
+        run: |
+          mvn clean test -DtestType=${{ inputs.testng_file }}
+          test_exit_code=$?
+          if [ $test_exit_code -ne 0 ]; then
+            echo "Tests failed"
+            exit $test_exit_code
+          fi
         continue-on-error: true
 
       - name: Archive report
